name: Deploy to Azure Web App - file-searching-ai-chatbot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Zip project for deployment
      run: zip -r app.zip . -x ".git/*" ".github/*" "venv/*" "__pycache__/*"

    - name: Deploy to Azure Web App using Publish Profile
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'file-searching-ai-chatbot'  # Replace with your app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './app.zip'
